server:
  port: 9090

spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
